config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "employees#index"

	# RESTful routes
	resources :employees

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, length: { minimum: 7 }
  validates :job, length: { minimum: 15 }
  validates :department, length: { in: 15..50 }
  validates :salary, numericality: {greater_than_or_equal_to: 0}
  validates :hire_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      flash[:success] = "Employee created successfully"
      redirect_to @employee
    else
      flash.now[:danger] = "An error has occured while creating employee"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:success] = "Employee updated successfully"
      redirect_to @employee
    else
      flash.now[:danger] = "An error has occured while updating employee"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.present?
      @employee.destroy
      flash[:success] = "Employee deleted successfully"
    else
      flash[:danger] = "An error has occured while deleting employee"
    end
    redirect_to root_path
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :job, :department, :salary, :hire_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/_form.html.erb
<%= form_with model: employee do |form|%>

  <% if employee.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <% employee.errors.each do |error| %>
        <div>
          <%= error.full_message %>
        </div>
      <% end %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :job, class: "form-label" %>
    <%= form.text_field :job, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :department, class: "form-label" %>
    <%= form.text_field :department, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :salary, class: "form-label" %>
    <%= form.number_field :salary, class: "form-control", required: true, min: 0 %>
  </div>

  <div class="mb-3">
    <%= form.label :hire_date, class: "form-label" %>
    <%= form.date_field :hire_date, class: "form-control", required: true %>
  </div>
  <div class="mb-3 d-flex justify-content-between">
    <%= form.submit class: "btn btn-primary order-1" %>
    <%= link_to root_path, class: "btn btn-primary order-0" do %>
      <i class="bi bi-arrow-left-short"></i> Back
    <% end %>
  </div>
  <% end %>

app/views/employees/edit.html.erb
<div class="row">
  <div class="col col-md-7 mx-auto">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h3 class="text-center my-3">Edit Employee</h3>
      </div>
      <div class="card-body">
        <%= render "form", employee: @employee %>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
  <div class="col col-md-7 mx-auto">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h3 class="text-center my-3">Employees</h3>
      </div>
      <div class="card-body">
        <div class="d-flex justify-content-end mb-2">
          <%= link_to new_employee_path, class: "btn btn-primary" do %>
            <i class="bi bi-plus-lg"></i> New Employee
          <% end %>
        </div>
        <div class="table-responsive">
          <table class="table align-middle">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col" class="d-flex justify-content-center">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @employees.each_with_index do |employee, index| %>
                <tr>
                  <th scope="row"><%= index+1 %></th>
                  <td><%= link_to employee.name, employee, class: "btn btn-link" %></td>
                  <td class="d-flex justify-content-center gap-1">
                    <%= link_to edit_employee_path(employee), class: "btn btn-success" do %>
                      <i class="bi bi-pencil-square"></i> Edit
                    <% end %>
                    <%= link_to employee_path(employee), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" do %>
                      <i class="bi bi-trash"></i> Delete
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="row">
  <div class="col col-md-7 mx-auto">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h3 class="text-center my-3">New Employee</h3>
      </div>
      <div class="card-body">
        <%= render "form", employee: @employee %>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="row">
  <div class="col col-md-7 mx-auto">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h3 class="text-center my-3">Employee Details</h3>
      </div>
      <div class="card-body">
        <dl class="row">
          <dt class="col-sm-3">Name:</dt>
          <dd class="col-sm-9"><%= @employee.name %></dd>

          <dt class="col-sm-3">Job:</dt>
          <dd class="col-sm-9"><%= @employee.job %></dd>

          <dt class="col-sm-3">Department:</dt>
          <dd class="col-sm-9"><%= @employee.department %></dd>

          <dt class="col-sm-3 text-truncate">Salary:</dt>
          <dd class="col-sm-9"><%= @employee.salary %></dd>

          <dt class="col-sm-3 text-truncate">Hire Date:</dt>
          <dd class="col-sm-9"><%= @employee.hire_date %></dd>
        </dl>
      </div>
      <div class="card-footer d-flex justify-content-center gap-1">
        <%= link_to root_path, class: "btn btn-primary" do %>
          <i class="bi bi-arrow-left-short"></i> Back
        <% end %>
        <%= link_to edit_employee_path(@employee), class: "btn btn-success" do %>
          <i class="bi bi-pencil-square"></i> Edit
        <% end %>
        <%= link_to employee_path(@employee), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" do %>
          <i class="bi bi-trash"></i> Delete
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assessment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container p-3">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%=type%> alert-dismissible fade show mb-2" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>